name: Build DockDigits Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri deps
        run: brew install create-dmg

      - name: Build Tauri App
        run: bun run tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockdigits-build
          path: src-tauri/target/release/bundle
